# ===================================
#  List Behavior Config
# ===================================

title: void.comic::lang.comics.list_title
list: ~/plugins/void/comic/models/comic/columns.yaml
modelClass: Void\Comic\Models\Comic
recordUrl: void/comic/comics/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showCheckboxes: true
showSetup: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt



